version: '3.8'
services:
  book-storage-service:
    image: book-storage-service:1.0
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-storage:5432/book-storage-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=DBPASSWORD
    depends_on:
      - db-storage
    ports:
      - "8080:8080"

  book-tracker-service:
    image: book-tracker-service:1.0
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-tracker:5432/book-tracker-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=DBPASSWORD
    depends_on:
      - db-tracker
    ports:
      - "8000:8080"

  auth-service:
    image: auth-service:1.0
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-storage:5432/auth-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=DBPASSWORD
    depends_on:
      - db-auth
    ports:
      - "8008:8080"

  db-storage:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: book_storage_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  db-tracker:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: book_tracker_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"

  db-auth:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
