version: '3.8'
services:
  book-storage-service:
    build:
      context: ./book-storage-service
      dockerfile: Dockerfile
    image: book-storage-service:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-storage:5432/book_storage_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=DBPASSWORD
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
      - db-storage
    ports:
      - "8080:8080"

  book-tracker-service:
    build:
      context: ./book-tracker-service
      dockerfile: Dockerfile
    image: book-tracker-service:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-tracker:5432/book_tracker_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=DBPASSWORD
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
      - db-tracker
    ports:
      - "8000:8000"

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: auth-service:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-auth:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=DBPASSWORD
    depends_on:
      - kafka
      - db-auth
    ports:
      - "8008:8008"

  db-storage:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: book_storage_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DBPASSWORD
    ports:
      - "5433:5432"

  db-tracker:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: book_tracker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DBPASSWORD
    ports:
      - "5434:5432"

  db-auth:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DBPASSWORD
    ports:
      - "5435:5432"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://library-kafka-1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
